baseurl = "https://cinaq.com/"
languageCode = "en-us"
title = "CINAQ"
googleAnalytics = "UA-74177616-1"
disqusShortname = "cinaq"
theme = "hugo-ink"
paginate = 5

copyright = "Copy responsibly; give credit"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	author = "Xiwen Cheng"
	subtitle = "Food for thought"

	# Optional 64x64 avatar image.
	avatar = "/images/xiwen.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/post"
weight = 2

[[menu.main]]
name = "Photography"
url = "/photography"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/xiwenc"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "http://nl.linkedin.com/in/xiwen"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://www.twitter.com/xiwenc"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[permalinks]
    post = "/post/:year/:month/:day/:title/"
    page = "/:title/"
