baseURL = "/"
languageCode = "en-us"
title = "CINAQ"
theme = "hugo-paradigm"
enableGitInfo = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
paginate = 6

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    work =  "works"
    author = "authors"

[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
  
# Main Menu

[[menu.main]]
    name = "Services"
    url = "/services"
    weight = 3
    identifier = 'dropdown_services'
    [[menu.main]]
        name = "Cloud Consultancy"
        url = "/services/cloud-consultancy"
        parent = "dropdown_services"
        weight = 1
    [[menu.main]]
        name = "Mendix Deployment"
        url = "/services/mendix-deployment"
        parent = "dropdown_services"
        weight = 3

[[menu.main]]
	name = "Low-Ops"
	url = "https://low-ops.com"
    weight = 1
#    identifier = 'dropdown_products'

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
    weight = 1
[[menu.footer_primary]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.footer_primary]]
    name = "About Us"
    url = "/about-us"
    weight = 3
[[menu.footer_primary]]
    name = "Contact Us"
    url = "/contact-us"
    weight = 4
[[menu.footer_primary]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 5

# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "Low-Ops"
    url = "https://low-ops.com"
    weight = 1
[[menu.footer_secondary]]
    name = "mendix-cli"
    url = "https://github.com/cinaq/mendix-cli"
    weight = 3
[[menu.footer_secondary]]
    name = "mendix-userlib-cleaner"
    url = "https://github.com/cinaq/mendix-userlib-cleaner"
    weight = 3
[[menu.footer_secondary]]
    name = "Photography"
    url = "/photography"
    weight = 4
