baseURL = "/"
languageCode = "en-us"
title = "CINAQ"
theme = "hugo-paradigm"
enableGitInfo = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
paginate = 6

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    work =  "works"
    author = "authors"

[frontmatter]
    date = ['date', 'publishDate', 'lastmod']
    expiryDate = ['expiryDate']
    lastmod = [':git', 'lastmod', 'date', 'publishDate']
    publishDate = ['publishDate', 'date']
  
# Main Menu

[[menu.main]]
    name = "Services"
    url = "/services"
    weight = 1
    identifier = 'dropdown_services'
    [[menu.main]]
        name = "Cloud Consultancy"
        url = "/services/cloud-consultancy"
        parent = "dropdown_services"
        weight = 1
    [[menu.main]]
        name = "Mendix Security Assessment"
        url = "/services/mendix-security-assessment"
        parent = "dropdown_services"
        weight = 2
    [[menu.main]]
        name = "Mendix Deployment"
        url = "/services/mendix-deployment"
        parent = "dropdown_services"
        weight = 3

#[[menu.main]]
#	name = "Products"
#	url = "/products"
#    weight = 2
#    identifier = 'dropdown_products'
    [[menu.main]]
        name = "AppSec"
        url = "/appsec"
#        parent = "dropdown_products"
        weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
    weight = 1
[[menu.footer_primary]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.footer_primary]]
    name = "About Us"
    url = "/about-us"
    weight = 3
[[menu.footer_primary]]
    name = "Contact Us"
    url = "/contact-us"
    weight = 4
[[menu.footer_primary]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 5

# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "AppSec"
    url = "/appsec"
    weight = 1
[[menu.footer_secondary]]
    name = "HackMe"
    url = "https://github.com/cinaq/hackme"
    weight = 2
[[menu.footer_secondary]]
    name = "Fastpush"
    url = "https://github.com/xiwenc/fastpush"
    weight = 3
[[menu.footer_secondary]]
    name = "Photography"
    url = "/photography"
    weight = 4
