name: Publish
on:
  push:
    branches: 
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and publish
      run: |
        git config --global user.name 'Robot'
        git config --global user.email 'robot@cinaq.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        make publish